<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Preface | Understanding Uncertainty Course Notes</title>
<meta name="author" content="Jeffrey Woo">
<meta name="description" content="DS 5030">
<meta name="generator" content="bookdown 0.43 with bs4_book()">
<meta property="og:title" content="Preface | Understanding Uncertainty Course Notes">
<meta property="og:type" content="book">
<meta property="og:description" content="DS 5030">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Preface | Understanding Uncertainty Course Notes">
<meta name="twitter:description" content="DS 5030">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Understanding Uncertainty Course Notes</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="active" href="index.html">Preface</a></li>
<li><a class="" href="descriptive.html"><span class="header-section-number">1</span> Descriptive Statistics</a></li>
<li><a class="" href="probability.html"><span class="header-section-number">2</span> Probability</a></li>
<li><a class="" href="discrete-random-variables.html"><span class="header-section-number">3</span> Discrete Random Variables</a></li>
<li><a class="" href="continuous-random-variables.html"><span class="header-section-number">4</span> Continuous Random Variables</a></li>
<li><a class="" href="joint-distributions.html"><span class="header-section-number">5</span> Joint Distributions</a></li>
<li><a class="" href="inequalities-limit-theorems-and-simulations.html"><span class="header-section-number">6</span> Inequalities, Limit Theorems, and Simulations</a></li>
<li><a class="" href="est.html"><span class="header-section-number">7</span> Estimation</a></li>
<li><a class="" href="confidence-intervals.html"><span class="header-section-number">8</span> Confidence Intervals</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><!--bookdown:title:end--><!--bookdown:title:start--><div id="preface" class="section level1 unnumbered">
<h1>Preface<a class="anchor" aria-label="anchor" href="#preface"><i class="fas fa-link"></i></a>
</h1>
<p>The examples in this preface is based on OpenIntro Statistics (Diez, Ceytinka-Rundel, Barr), Chapter 9.4 and 9.5, which provide more background information. You can access the book for free at <a href="https://www.openintro.org/book/os/" class="uri">https://www.openintro.org/book/os/</a></p>
<p>The main goal using data science is to understand data. Broadly speaking, this will involve building a statistical model for predicting, or estimating a response variable based on one or more predictors. Such models are used in a wide variety of fields such as finance, medicine, public policy, sports, and so on. We will look a couple of examples.</p>
<div id="examples" class="section level2" number="0.1">
<h2>
<span class="header-section-number">0.1</span> Examples<a class="anchor" aria-label="anchor" href="#examples"><i class="fas fa-link"></i></a>
</h2>
<div id="example-1-mario-kart-auction-prices" class="section level3" number="0.1.1">
<h3>
<span class="header-section-number">0.1.1</span> Example 1: Mario Kart Auction Prices<a class="anchor" aria-label="anchor" href="#example-1-mario-kart-auction-prices"><i class="fas fa-link"></i></a>
</h3>
<p>In this first example, we will look at Ebay auctions of a video game called Mario Kart that is played on Nintendo Wii. We want to predict the price of an auction based on whether the game is new or not, whether the auction’s main photo is a stock photo, the duration of the auction in days, and the number of Wii wheels included with the auction.</p>
<p>A model that we can use for this example is the linear regression model:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://openintrostat.github.io/openintro/">openintro</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">Data</span><span class="op">&lt;-</span><span class="va">mariokart</span></span>
<span><span class="co">##fit model</span></span>
<span><span class="va">result</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">total_pr</span><span class="op">~</span><span class="va">cond</span><span class="op">+</span><span class="va">stock_photo</span><span class="op">+</span><span class="va">duration</span><span class="op">+</span><span class="va">wheels</span>, data<span class="op">=</span><span class="va">Data</span><span class="op">)</span></span></code></pre></div>
<p>Generally speaking, a linear regression equation takes the following form:</p>
<p><span class="math display">\[
\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2 + \cdots + \hat{\beta}_k x_k
\]</span></p>
<p>where <span class="math inline">\(\hat{y}\)</span> denotes the predicted value of the response variable, the price of the action in this example, <span class="math inline">\(x_1, x_2, \cdots, x_k\)</span> denote the values of the predictors. This is example, we have: <span class="math inline">\(x_1\)</span> for whether the game is new or not, <span class="math inline">\(x_2\)</span> for whether the auction’s main photo is a stock photo, <span class="math inline">\(x_3\)</span> for the duration of the auction in days, and <span class="math inline">\(x_4\)</span> for the number of Wii wheels included with the auction. <span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \cdots, \hat{\beta}_k\)</span> represent the estimated regression parameters. If we know what these values are, we can easily plug in the values of the predictors to obtain the predicted price of the auction.</p>
<p>Fitting the model in R, we obtain the estimated regression parameters:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">##get estimated regression parameters</span></span>
<span><span class="va">result</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = total_pr ~ cond + stock_photo + duration + wheels, 
##     data = Data)
## 
## Coefficients:
##    (Intercept)        condused  stock_photoyes        duration          wheels  
##        43.5201         -2.5816         -6.7542          0.3788          9.9476</code></pre>
<p>so we have:</p>
<p><span class="math display">\[
\hat{y} = 43.5201 - 2.5816 x_1 - 6.7542 x_2 + 0.3788 x_3 + 9.9476 x_4
\]</span></p>
<p>So for an auction for Mario Kart game that is used, that uses a stock photo, is listed for 2 days, and comes with 0 wheels, the predicted price will be <span class="math inline">\(\hat{y} = 43.5201 - 2.5816 - 6.7542 + 0.3788 \times 2 = 34.94\)</span> or about 35 dollars.</p>
</div>
<div id="eg2" class="section level3" number="0.1.2">
<h3>
<span class="header-section-number">0.1.2</span> Example 2: Job Application Callback Rates<a class="anchor" aria-label="anchor" href="#eg2"><i class="fas fa-link"></i></a>
</h3>
<p>In this example, we look at data from an experiment that sought to evaluate the effect of race and gender on job application callback rates. For the experiment, researchers created fake resumes to job postings in Boston and Chicago to see which resumes resulted in a callback. The fake resumes included relevant information such as the applicant’s educational attainment, how many year’s of experience the applicant as well as a first and last name. The names on the fake resume were meant to imply the applicant’s race and gender. Only two races were considered (Black or White) and only two genders were considered (Make or Female) for the experiment.</p>
<p>Prior to the experiment, the researchers conducted surveys to check for racial and gender associations for the names on the fake resumes; only names that passed a certain threshold from the surveys were included in the experiment.</p>
<p>A model that can be used in this example is the logistic regression model</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Data2</span><span class="op">&lt;-</span><span class="va">resume</span></span>
<span><span class="co">##fit model</span></span>
<span><span class="va">result2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">received_callback</span><span class="op">~</span><span class="va">job_city</span> <span class="op">+</span> <span class="va">college_degree</span><span class="op">+</span><span class="va">years_experience</span><span class="op">+</span><span class="va">race</span><span class="op">+</span><span class="va">gender</span>, family<span class="op">=</span><span class="st">"binomial"</span>, data<span class="op">=</span><span class="va">Data2</span><span class="op">)</span></span></code></pre></div>
<p>Generally speaking, a logistic regression equation takes the following form</p>
<p><span class="math display">\[
\log (\frac{\hat{\pi}}{1-\hat{\pi}}) = \hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2 + \cdots + \hat{\beta}_k x_k
\]</span></p>
<p>where <span class="math inline">\(\hat{\pi}\)</span> denotes the predicted probability that the applicant receives a call back. <span class="math inline">\(x_1, x_2, \cdots, x_k\)</span> denote the values of the predictors. This is example, we have: <span class="math inline">\(x_1\)</span> for which city is the job posting located in, <span class="math inline">\(x_2\)</span> for whether the applicant has a college degree or not, <span class="math inline">\(x_3\)</span> for the experience of the applicant, <span class="math inline">\(x_4\)</span> for associated race of the applicant, and <span class="math inline">\(x_5\)</span> for the associated gender of the applicant. Similar to linear regression, <span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \cdots, \hat{\beta}_k\)</span> represent the estimated regression parameters. If we know what these values are, we can easily plug in the values of the predictors to obtain the predicted probability for an applicant with those characteristics to receive a callback.</p>
<p>Fitting the model in R, we obtain the estimated regression parameters</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">##get estimated regression parameters</span></span>
<span><span class="va">result2</span></span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = received_callback ~ job_city + college_degree + 
##     years_experience + race + gender, family = "binomial", data = Data2)
## 
## Coefficients:
##      (Intercept)   job_cityChicago    college_degree  years_experience  
##         -2.63974          -0.39206          -0.06550           0.03152  
##        racewhite           genderm  
##          0.44299          -0.22814  
## 
## Degrees of Freedom: 4869 Total (i.e. Null);  4864 Residual
## Null Deviance:       2727 
## Residual Deviance: 2680  AIC: 2692</code></pre>
<p>so we have</p>
<p><span class="math display">\[
\log (\frac{\hat{\pi}}{1-\hat{\pi}}) = -2.63974 - 0.39206 x_1 - 0.0655 x_2 + 0.03152 x_3 + 0.44299 x_4 - 0.22814 x_5
\]</span></p>
<p>So for an applicant in Boston, who has a college degree, has 10 years of experience and has a name that is associated with being a Black male, the logistic regression equation becomes <span class="math inline">\(\log (\frac{\hat{\pi}}{1-\hat{\pi}}) = -2.63974 - 0.0655 + 0.03152 \times 10 - 0.22814 = -2.61818\)</span>. Doing a little bit of algebra to solve, we get <span class="math inline">\(\hat{\pi} = 0.06797751\)</span>. Such an applicant has about a 6.8 percent chance of receiving a callback.</p>
</div>
</div>
<div id="how-were-estimated-parameters-calculated" class="section level2" number="0.2">
<h2>
<span class="header-section-number">0.2</span> How were Estimated Parameters Calculated?<a class="anchor" aria-label="anchor" href="#how-were-estimated-parameters-calculated"><i class="fas fa-link"></i></a>
</h2>
<p>In the two examples, notice how I used some R functions, supplied the names of the variables, and the R functions generated the values of the estimated parameters? One thing you will learn is how the functions actually calculate these numbers. It turns out that these calculations are based on foundational concepts associated with measures of uncertainty, probability, and expected values. We will be learning about these concepts in this class.</p>
<p>Why do we want to know how these calculations are performed? So that we understand the intuition and logic behind how these models are built. It becomes a lot easier to work with these models when we understand their logic (for example, we know when these models can be used or cannot be used, we know what steps to take when we notice our data have certain characteristics, etc), instead of memorizing a bunch of steps.</p>
<p>When presenting models and data to people, some people may occasionally questions our methods and models. Why should we trust the model? Should we trust these numbers that seem to come out from some black box?</p>
<p>Notice we used two different models, linear regression and logistic regression, for examples 1 and 2. Why did we use these models? Could we have swapped the type of model used in these examples? The answer is actually no. One of the main considerations when deciding what model to use is to identify if our response variable is quantitative or categorical. You will learn why the linear regression model works when the response variable is quantitative, and why the logistic regression model works when the response variable is categorical.</p>
</div>
<div id="the-course-understanding-uncertainty" class="section level2" number="0.3">
<h2>
<span class="header-section-number">0.3</span> The Course: Understanding Uncertainty<a class="anchor" aria-label="anchor" href="#the-course-understanding-uncertainty"><i class="fas fa-link"></i></a>
</h2>
<p>As mentioned in the previous section, we will be learning about foundational concepts associated with measures of uncertainty, probability, and expected values. All of these concepts will then help explain the intuition and how statistical models are built.</p>
<p>At the end of the course, we will apply these concepts and revisit the linear regression and logistic regression models. These are two of the most widely used models used in data science, as they are relatively easier to understand and explain. More modern methods (that you will learn about in future classes) such as decision trees and neural networks can be viewed as extensions of the linear and logistic regression models.</p>

</div>
</div>
  <div class="chapter-nav">
<div class="empty"></div>
<div class="next"><a href="descriptive.html"><span class="header-section-number">1</span> Descriptive Statistics</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#preface">Preface</a></li>
<li>
<a class="nav-link" href="#examples"><span class="header-section-number">0.1</span> Examples</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#example-1-mario-kart-auction-prices"><span class="header-section-number">0.1.1</span> Example 1: Mario Kart Auction Prices</a></li>
<li><a class="nav-link" href="#eg2"><span class="header-section-number">0.1.2</span> Example 2: Job Application Callback Rates</a></li>
</ul>
</li>
<li><a class="nav-link" href="#how-were-estimated-parameters-calculated"><span class="header-section-number">0.2</span> How were Estimated Parameters Calculated?</a></li>
<li><a class="nav-link" href="#the-course-understanding-uncertainty"><span class="header-section-number">0.3</span> The Course: Understanding Uncertainty</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Understanding Uncertainty Course Notes</strong>" was written by Jeffrey Woo. It was last built on 2025-07-21.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
